//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpareShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int ThingId { get; set; }
        public int ReceiverId { get; set; }
        public string Text { get; set; }
        public Nullable<int> NewScore { get; set; }
        public Nullable<int> SimilarScore { get; set; }
        public Nullable<int> UsefulScore { get; set; }
        public Nullable<int> SpeedScore { get; set; }
        public Nullable<int> BeautifulScore { get; set; }
        public Nullable<System.DateTime> CommentTime { get; set; }
    }
}
