//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpareShareMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Things
    {
        public int ThingId { get; set; }
        public Nullable<int> GiverId { get; set; }
        public Nullable<int> CheckId { get; set; }
        public string Name { get; set; }
        public string Reason { get; set; }
        public string Type { get; set; }
        public string PhotoURL { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public Nullable<System.DateTime> DealTime { get; set; }
    }
}
